#!/bin/bash -e
#===============================================================================
# Pad 4D timeseries in 3 dimensions (x,y,z)
# Authors: Timothy R. Koscik
# Date: 2021-03-11
#===============================================================================
PROC_START=$(date +%Y-%m-%dT%H:%M:%S%z)
FCN_NAME=($(basename "$0"))
DATE_SUFFIX=$(date +%Y%m%dT%H%M%S%N)
OPERATOR=$(whoami)
KERNEL="$(uname -s)"
HARDWARE="$(uname -m)"
HPC_Q=${QUEUE}
HPC_SLOTS=${NSLOTS}
KEEP=false
NO_LOG=false
umask 007

# actions on exit, write to logs, clean scratch
function egress {
  EXIT_CODE=$?
  PROC_STOP=$(date +%Y-%m-%dT%H:%M:%S%z)
  if [[ "${KEEP}" == "false" ]]; then
    if [[ -n ${DIR_SCRATCH} ]]; then
      if [[ -d ${DIR_SCRATCH} ]]; then
        if [[ "$(ls -A ${DIR_SCRATCH})" ]]; then
          rm -R ${DIR_SCRATCH}
        else
          rmdir ${DIR_SCRATCH}
        fi
      fi
    fi
  fi
  if [[ "${NO_LOG}" == "false" ]]; then
    unset LOGSTR
    LOGSTR="${OPERATOR},${DIR_PROJECT},${PID},${SID},${HARDWARE},${KERNEL},${HPC_Q},${HPC_SLOTS},${FCN_NAME},${PROC_START},${PROC_STOP},${EXIT_CODE}"
    writeLog --benchmark --string ${LOGSTR}
  fi
}
trap egress EXIT

# Parse inputs -----------------------------------------------------------------
OPTS=$(getopt -o hl --long ts:,pad:,dir-save:,dir-scratch:,\
help,no-log -n 'parse-options' -- "$@")
if [ $? != 0 ]; then
  echo "Failed parsing options" >&2
  exit 1
fi
eval set -- "$OPTS"

# Set default values for function ---------------------------------------------
PREFIX=
TS=
PAD=5
DIR_SAVE=
DIR_SCRATCH=${INC_SCRATCH}/${OPERATOR}_${DATE_SUFFIX}
HELP=false

while true; do
  case "$1" in
    -h | --help) HELP=true ; shift ;;
    -l | --no-log) NO_LOG=true ; shift ;;
    --prefix) PREFIX="$2" ; shift 2 ;;
    --ts) TS="$2" ; shift 2 ;;
    --pad) PAD="$2" ; shift 2 ;;
    --dir-save) DIR_SAVE="$2" ; shift 2 ;;
    --dir-scratch) DIR_SCRATCH="$2" ; shift 2 ;;
    -- ) shift ; break ;;
    * ) break ;;
  esac
done

# Usage Help -------------------------------------------------------------------
if [[ "${HELP}" == "true" ]]; then
  echo ''
  echo '------------------------------------------------------------------------'
  echo "Iowa Neuroimage Processing Core: ${FCN_NAME}"
  echo '------------------------------------------------------------------------'
  echo '  -h | --help              display command help'
  echo '  -l | --no-log            disable writing to output log'
  echo '  --prefix  <optional>     filename, without extension to use for file'
  echo '  --ts                     input 4D timeseries to pad'
  echo '  --pad                    number of voxels to use for padding'
  echo '  --dir-save               location to save output'
  echo '  --dir-scratch            location for temporary files'
  echo ''
  NO_LOG=true
  exit 0
fi

#===============================================================================
# Start of Function
#===============================================================================
# Set up BIDs compliant variables and workspace --------------------------------
DIR_PROJECT=$(getDir -i ${TS})
PID=$(getField -i ${TS} -f sub)
SID=$(getField -i ${TS} -f ses)
PIDSTR=sub-${PID}
DIRPID=sub-${PID}
if [[ -n ${SID} ]]; then PIDSTR="${PIDSTR}_ses-${SID}"; fi
if [[ -n ${SID} ]]; then DIRPID="${DIRPID}/ses-${SID}"; fi

if [[ -z ${PREFIX} ]]; then
  PREFIX=$(getBidsBase -i ${TS})
  PREP=$(getField -i ${PREFIX} -f prep)
  if [[ -n ${PREP} ]]; then
    PREFIX=$(modField -i ${PREFIX} -m -f prep -v "${PREP}+pad${PAD}")
  else
    PREFIX=$(modField -i ${PREFIX} -a -f prep -v "pad${PAD}")
  fi
fi

if [[ -z ${DIR_SAVE} ]]; then
  DIR_SAVE=${DIR_PROJECT}/derivatives/inc/func/prep/${DIRPID}
fi
mkdir -p ${DIR_SAVE}
mkdir -p ${DIR_SCRATCH}

# get necessary timing info ----------------------------------------------------
TR=$(niiInfo -i ${TS} -f TR)
NTR=$(niiInfo -i ${TS} -f numTR)
if [[ ${NTR} -eq 1 ]]; then
  echo "ERROR: only 1 TR identified in ${TS}, aborting processing"
  exit 1
fi

# split image into volumes for each TR -----------------------------------------
fslsplit ${TS} ${DIR_SCRATCH}/v -t

# pad each volume in 3D space --------------------------------------------------
for (( i=0; i<${NTR}; i++ )); do
  NV=$(printf "%04d" ${i})
  ImageMath 3 ${DIR_SCRATCH}/v${NV}.nii.gz \
    PadImage ${DIR_SCRATCH}/v${NV}.nii.gz ${PAD}
done

# merge padded files back together ---------------------------------------------
MERGE_LS=($(ls ${DIR_SCRATCH}/v*))
fslmerge -tr ${DIR_SAVE}/${PREFIX}.nii.gz ${MERGE_LS[@]} ${TR}

#===============================================================================
# End of Function
#===============================================================================
exit 0

