#!/bin/bash -e
#===============================================================================
# Functional Timeseries - Anatomical CompCorr
# Authors: Timothy R. Koscik
# Date: 2021-03-18
#===============================================================================
PROC_START=$(date +%Y-%m-%dT%H:%M:%S%z)
FCN_NAME=($(basename "$0"))
DATE_SUFFIX=$(date +%Y%m%dT%H%M%S%N)
OPERATOR=$(whoami)
KERNEL="$(uname -s)"
HARDWARE="$(uname -m)"
HPC_Q=${QUEUE}
HPC_SLOTS=${NSLOTS}
KEEP=false
NO_LOG=false
umask 007

# actions on exit, write to logs, clean scratch
function egress {
  EXIT_CODE=$?
  PROC_STOP=$(date +%Y-%m-%dT%H:%M:%S%z)
  if [[ "${KEEP}" == "false" ]]; then
    if [[ -n ${DIR_SCRATCH} ]]; then
      if [[ -d ${DIR_SCRATCH} ]]; then
        if [[ "$(ls -A ${DIR_SCRATCH})" ]]; then
          rm -R ${DIR_SCRATCH}
        else
          rmdir ${DIR_SCRATCH}
        fi
      fi
    fi
  fi
  if [[ "${NO_LOG}" == "false" ]]; then
    unset LOGSTR
    LOGSTR="${OPERATOR},${DIR_PROJECT},${PID},${SID},${HARDWARE},${KERNEL},${HPC_Q},${HPC_SLOTS},${FCN_NAME},${PROC_START},${PROC_STOP},${EXIT_CODE}"
    writeLog --benchmark --string ${LOGSTR}
  fi
}
trap egress EXIT

# Parse inputs -----------------------------------------------------------------
OPTS=$(getopt -o hln: --long prefix:,ts:,n-components:,label:,csf:,wm:,\
dir-save:,dir-scratch:,help,no-log -n 'parse-options' -- "$@")
if [[ $? != 0 ]]; then
  echo "Failed parsing options" >&2
  exit 1
fi
eval set -- "$OPTS"

# Set default values for function ---------------------------------------------
PREFIX=
TS=
N=5
LABEL=
CSF=1
WM=3
DIR_SAVE=
DIR_SCRATCH=${INC_SCRATCH}/${OPERATOR}_${DATE_SUFFIX}
HELP=false
NO_LOG=false

while true; do
  case "$1" in
    -h | --help) HELP=true ; shift ;;
    -l | --no-log) NO_LOG=true ; shift ;;
    --prefix) PREFIX="$2" ; shift 2 ;;
    --ts) TS="$2" ; shift 2 ;;
    -n | --n-components) N="$2" ; shift 2 ;;
    --label) LABEL="$2" ; shift 2 ;;
    --csf) CSF="$2" ; shift 2 ;;
    --wm) WM="$2" ; shift 2 ;;
    --dir-save) DIR_SAVE="$2" ; shift 2 ;;
    --dir-scratch) SCRATCH="$2" ; shift 2 ;;
    -- ) shift ; break ;;
    * ) break ;;
  esac
done

# Usage Help -------------------------------------------------------------------
if [[ "${HELP}" == "true" ]]; then
  echo ''
  echo '------------------------------------------------------------------------'
  echo "Iowa Neuroimage Processing Core: ${FCN_NAME}"
  echo '------------------------------------------------------------------------'
  echo '  -h | --help              display command help'
  echo '  -l | --no-log            disable writing to output log'
  echo '  --prefix                 scan prefix, default: sub-123_ses-1234abcd'
  echo '  --ts                     Full path to single, run timeseries'
  echo '  -n | --n-components      number of components to extract, default=5'
  echo '  --label                  path to file containing tissue type labels'
  echo '  --csf                    numeric value indicating CSF, default=1'
  echo '  --wm                     numeric value indicating WM, default=3'
  echo '  --dir-save               directory to save output, default:'
  echo '           DIR_PROJECT/derivatives/inc/func/regressor/sub-###/ses-###'
  echo '  --dir-scratch <value>    directory for temporary workspace'
  echo ''
  NO_LOG=true
  exit 0
fi

#===============================================================================
# Start of Function
#===============================================================================
# Set up BIDs compliant variables and workspace --------------------------------
DIR_PROJECT=$(getDir -i ${TS})
PID=$(getField -i ${TS} -f sub)
SID=$(getField -i ${TS} -f ses)
if [[ ! -f "${TS}" ]]; then
  echo "The Time-series file does not exist. Exiting."
  exit 1
fi
DIRPID="sub-${PID}"
if [[ -n ${SID} ]]; then DIRPID="${DIRPID}/ses-${SID}"; fi
if [[ -z "${PREFIX}" ]]; then PREFIX=$(getBidsBase -s -i ${TS}); fi
if [[ -z "${DIR_SAVE}" ]]; then DIR_SAVE=${DIR_PROJECT}/derivatives/inc/func/regressor/${DIRPID}; fi
mkdir -p ${DIR_SAVE}

if [[ -z ${LABEL} ]]; then
  mkdir -p ${DIR_SCRATCH}
  antsApplyTransforms -d 3 -n MultiLabel \
    -i ${INC_TEMPLATE}/HCPICBM/700mm/HCPICBM_700mm_label-sCompCorr.nii.gz \
    -o ${DIR_SCRATCH}/temp_label-acompcorr.nii.gz \
    -r ${TS}
  LABEL=${DIR_SCRATCH}/temp_label-acompcorr.nii.gz
fi

3dmaskSVD -vnorm -polort 1 -sval ${N} -mask ${LABEL}"<${CSF}..${CSF}" ${TS} > ${DIR_SAVE}/${PREFIX}_compcorr+csf+${N}.1D
3dmaskSVD -vnorm -polort 1 -sval ${N} -mask ${LABEL}"<${WM}..${WM}" ${TS} > ${DIR_SAVE}/${PREFIX}_compcorr+wm+${N}.1D

sed -i 's/  */,/g' ${DIR_SAVE}/${PREFIX}_compcorr+csf+${N}.1D
sed -i 's/  */,/g' ${DIR_SAVE}/${PREFIX}_compcorr+wm+${N}.1D
sed -i 's/,//' ${DIR_SAVE}/${PREFIX}_compcorr+csf+${N}.1D
sed -i 's/,//' ${DIR_SAVE}/${PREFIX}_compcorr+wm+${N}.1D

#===============================================================================
# End of Function
#===============================================================================
exit 0


