#!/bin/bash -e
#===============================================================================
# Functional Timeseries - Anatomical CompCorr
# Authors: Timothy R. Koscik
# Date: 2020-03-27
#===============================================================================
PROC_START=$(date +%Y-%m-%dT%H:%M:%S%z)
FCN_NAME=($(basename "$0"))
DATE_SUFFIX=$(date +%Y%m%dT%H%M%S%N)
OPERATOR=$(whoami)
KERNEL="$(uname -s)"
HARDWARE="$(uname -m)"
HPC_Q=${QUEUE}
HPC_SLOTS=${NSLOTS}
KEEP=false
NO_LOG=false
umask 007

# actions on exit, write to logs, clean scratch
function egress {
  EXIT_CODE=$?
  PROC_STOP=$(date +%Y-%m-%dT%H:%M:%S%z)
  if [[ "${KEEP}" == "false" ]]; then
    if [[ -n ${DIR_SCRATCH} ]]; then
      if [[ -d ${DIR_SCRATCH} ]]; then
        if [[ "$(ls -A ${DIR_SCRATCH})" ]]; then
          rm -R ${DIR_SCRATCH}
        else
          rmdir ${DIR_SCRATCH}
        fi
      fi
    fi
  fi
  if [[ "${NO_LOG}" == "false" ]]; then
    unset LOGSTR
    LOGSTR="${OPERATOR},${DIR_PROJECT},${PID},${SID},${HARDWARE},${KERNEL},${HPC_Q},${HPC_SLOTS},${FCN_NAME},${PROC_START},${PROC_STOP},${EXIT_CODE}"
    writeLog --benchmark --string ${LOGSTR}
  fi
}
trap egress EXIT

# Parse inputs -----------------------------------------------------------------
OPTS=$(getopt -o hl --long prefix:,\
ts:,mask:,label:,csf:,wm:,\
dir-save:,dir-scratch:,\
help,no-log -n 'parse-options' -- "$@")
if [[ $? != 0 ]]; then
  echo "Failed parsing options" >&2
  exit 1
fi
eval set -- "$OPTS"

# Set default values for function ---------------------------------------------
PREFIX=
TS=
MASK=
LABEL=
CSF=1
WM=3
DIR_SAVE=
DIR_SCRATCH=${INC_SCRATCH}/${OPERATOR}_${DATE_SUFFIX}
HELP=false
NO_LOG=false

while true; do
  case "$1" in
    -h | --help) HELP=true ; shift ;;
    -l | --no-log) NO_LOG=true ; shift ;;
    --prefix) PREFIX="$2" ; shift 2 ;;
    --ts) TS="$2" ; shift 2 ;;
    --mask) MASK="$2" ; shift 2 ;;
    --label) LABEL="$2" ; shift 2 ;;
    --csf) CSF="$2" ; shift 2 ;;
    --wm) WM="$2" ; shift 2 ;;
    --dir-save) DIR_SAVE="$2" ; shift 2 ;;
    --dir-scratch) SCRATCH="$2" ; shift 2 ;;
    -- ) shift ; break ;;
    * ) break ;;
  esac
done

# Usage Help -------------------------------------------------------------------
if [[ "${HELP}" == "true" ]]; then
  echo ''
  echo '------------------------------------------------------------------------'
  echo "Iowa Neuroimage Processing Core: ${FCN_NAME}"
  echo '------------------------------------------------------------------------'
  echo '  -h | --help              display command help'
  echo '  -l | --no-log            disable writing to output log'
  echo '  --prefix                 scan prefix, default: sub-123_ses-1234abcd'
  echo '  --ts                     Full path to single, run timeseries'
  echo '  --label                  Full path to file containing tissue type labels'
  echo '  --csf                    numeric value indicating CSF in label file, default=1'
  echo '  --wm                     numeric value indicating WM in label file, default=3'
  echo '  --dir-save               directory to save output, default:'
  echo '                             DIR_PROJECT/derivatives/inc/func/regressor/sub-/ses-'
  echo '  --dir-scratch            directory for temporary workspace'
  echo ''
  NO_LOG=true
  exit 0
fi

#===============================================================================
# Start of Function
#===============================================================================
# Set up BIDs compliant variables and workspace --------------------------------
DIR_PROJECT=$(getDir -i ${TS})
PID=$(getField -i ${TS} -f sub)
SID=$(getField -i ${TS} -f ses)
if [[ ! -f "${TS}" ]]; then
  echo "The BOLD file does not exist. Exiting."
  exit 1
fi
DIRPID="sub-${PID}"
if [[ -n ${SID} ]]; then DIRPID="${DIRPID}/ses-${SID}"; fi
if [[ -z "${PREFIX}" ]]; then PREFIX=$(getBidsBase -s -i ${TS}); fi
if [[ -z "${DIR_SAVE}" ]]; then DIR_SAVE=${DIR_PROJECT}/derivatives/inc/func/regressors/${DIRPID}; fi
mkdir -p ${DIR_SCRATCH}
mkdir -p ${DIR_SAVE}

# ANTs 3 Tissue Regressors (aCompCorr) ----------------------------------------
ImageMath 4 ${DIR_SCRATCH}/temp.nii.gz ThreeTissueConfounds ${TS} ${LABEL} ${CSF} ${WM}
cat ${DIR_SCRATCH}/temp_compcorr.csv | tail -n+2 > ${DIR_SCRATCH}/temp.1D
cut -d, -f1-1 --complement ${DIR_SCRATCH}/temp.1D > ${DIR_SCRATCH}/${PREFIX}_tissueMeans.1D
sed -i 's/,/\t/g' ${DIR_SCRATCH}/${PREFIX}_tissueMeans.1D
mv ${DIR_SCRATCH}/${PREFIX}_tissueMeans.1D ${DIR_SAVE}/

if [[ -n ${MASK_BRAIN} ]]; then
  fslmeants -i ${TS} -o ${DIR_SCRATCH}/${PREFIX}_global.1D --label=${MASK}
  sed -i s/"  "/","/g ${DIR_SCRATCH}/${PREFIX}_global.1D
  sed -i s/",$"//g ${DIR_SCRATCH}/${PREFIX}_global.1D
  mv ${DIR_SCRATCH}/${PREFIX}_global.1D ${DIR_SAVE}/
fi

#===============================================================================
# End of Function
#===============================================================================
exit 0


