#!/bin/bash -e
#===============================================================================
# Brain Extraction
# Authors: Timothy R. Koscik, PhD
# Date: 2020-02-27
#===============================================================================
PROC_START=$(date +%Y-%m-%dT%H:%M:%S%z)
FCN_NAME=($(basename "$0"))
DATE_SUFFIX=$(date +%Y%m%dT%H%M%S%N)
OPERATOR=$(whoami)
KERNEL="$(uname -s)"
HARDWARE="$(uname -m)"
HPC_Q=${QUEUE}
HPC_SLOTS=${NSLOTS}
KEEP=false
NO_LOG=false
umask 007

# actions on exit, write to logs, clean scratch
function egress {
  EXIT_CODE=$?
  PROC_STOP=$(date +%Y-%m-%dT%H:%M:%S%z)
  if [[ "${KEEP}" == "false" ]]; then
    if [[ -n ${DIR_SCRATCH} ]]; then
      if [[ -d ${DIR_SCRATCH} ]]; then
        if [[ "$(ls -A ${DIR_SCRATCH})" ]]; then
          rm -R ${DIR_SCRATCH}
        else
          rmdir ${DIR_SCRATCH}
        fi
      fi
    fi
  fi
  if [[ "${NO_LOG}" == "false" ]]; then
    unset LOGSTR
    LOGSTR="${OPERATOR},${DIR_PROJECT},${PID},${SID},${HARDWARE},${KERNEL},${HPC_Q},${HPC_SLOTS},${FCN_NAME},${PROC_START},${PROC_STOP},${EXIT_CODE}"
    writeLog --benchmark --string ${LOGSTR}
  fi
}
trap egress EXIT

# Parse inputs -----------------------------------------------------------------
OPTS=$(getopt -o hvln --long prefix:,label:,\
image:,method:,suffix:,spatial-filter:,filter-radius:,automask-clip:,\
dir-save:,dir-scratch:,\
help,verbose,no-log -n 'parse-options' -- "$@")
if [[ $? != 0 ]]; then
  echo "Failed parsing options" >&2
  exit 1
fi
eval set -- "$OPTS"

# Set default values for function ---------------------------------------------
PREFIX=
LABEL=brain
IMAGE=
METHOD=
SUFFIX=
SPATIAL_FILTER=null
FILTER_RADIUS=1
TEMPLATE="OASIS"
AUTOMASK_CLIP=0.5
DIR_SAVE=
DIR_SCRATCH=${INC_SCRATCH}/${OPERATOR}_${DATE_SUFFIX}
HELP=false
VERBOSE=false
NO_PNG=false

while true; do
  case "$1" in
    -h | --help) HELP=true ; shift ;;
    -v | --verbose) VERBOSE=true ; shift ;;
    -l | --no-log) NO_LOG=true ; shift ;;
    -n | --no-png) NO_PNG=true ; shift ;;
    --prefix) PREFIX="$2" ; shift 2 ;;
    --label) LABEL="$2" ; shift 2 ;;
    --image) IMAGE="$2" ; shift 2 ;;
    --method) METHOD="$2" ; shift 2 ;;
    --suffix) SUFFIX="$2" ; shift 2 ;;
    --spatial-filter) SPATIAL_FILTER="$2" ; shift 2 ;;
    --filter-radius) FILTER_RADIUS="$2" ; shift 2 ;;
    --automask-clip) AUTOMASK_CLIP="$2" ; shift 2 ;;
    --template) TEMPLATE="$2" ; shift 2 ;;
    --dir-save) DIR_SAVE="$2" ; shift 2 ;;
    --dir-scratch) DIR_SCRATCH="$2" ; shift 2 ;;
    -- ) shift ; break ;;
    * ) break ;;
  esac
done

# Usage Help -------------------------------------------------------------------
if [[ "${HELP}" == "true" ]]; then
  echo ''
  echo '------------------------------------------------------------------------'
  echo "Iowa Neuroimage Processing Core: ${FCN_NAME}"
  echo '------------------------------------------------------------------------'
  echo '  -h | --help        display command help'
  echo '  -v | --verbose     add verbose output to log file'
  echo '  -l | --no-log      disable writing to output log'
  echo '  -n | --no-png      disable generating pngs of output'
  echo '  --prefix           scan prefix, default: sub-123_ses-1234abcd'
  echo '  --label            label to append to mask names, e.g., mask-${LABEL}'
  echo '  --image            Images to use for brain extraction, multiple images'
  echo '                     allowed, T1w should be first input'
  echo '  --method           One of AFNI, ANTs, FSL, multiple inputs allowed.'
  echo '                     If multiple inputs given, a majority vote output'
  echo '                     and Venn-like overlap will be given as well'
  echo '  --suffix           an optional suffix to append to filenames,'
  echo '                     e.g., "0" or "prelim"'
  echo '  --spatial-filter   Add a spatial filter step after extracting mask'
  echo '                     using ImageMath, e.g., MD for dilation, filter'
  echo '                     radius must be specified as well.'
  echo '                     Recommended options are: MD, ME'
  echo '   WARNING: As of 2021-07-02 the ImageMath implementation of MO and MC'
  echo '            do not yield expected results on certain integer types.'
  echo '            Better practice is to perform these operations'
  echo '            independently afterward.'
  echo '  --filter-radius    Filter radius in voxels (unless filter is G for'
  echo '                     Gaussian then mm)'
  echo '  --automask-clip    threshold value for AFNI based methods'
  echo '  --template         For ANTs, which template to use, default=OASIS'
  echo '  --dir-save         directory to save output'
  echo '  --dir-scratch      directory for temporary workspace'
  echo ''
  NO_LOG=true
  exit 0
fi

#===============================================================================
# Start of Function
#===============================================================================
IMAGE=(${IMAGE//,/ })

# Set up BIDs compliant variables and workspace --------------------------------
DIR_PROJECT=$(getDir -i ${IMAGE[0]})
PID=$(getField -i ${IMAGE[0]} -f sub)
SID=$(getField -i ${IMAGE[0]} -f ses)
DIRPID=sub-${PID}
if [[ -n ${SID} ]]; then DIRPID="${DIRPID}/ses-${SID}"; fi
if [[ -z "${PREFIX}" ]]; then PREFIX=$(getBidsBase -s -i ${IMAGE[0]}); fi
if [[ -z "${DIR_SAVE}" ]]; then DIR_SAVE=${DIR_PROJECT}/derivatives/inc/prep/${DIRPID}/anat; fi
mkdir -p ${DIR_SCRATCH}
mkdir -p ${DIR_SAVE}

# Brain extraction ------------------------------------------------------------
# run AFNI 3dSkullStrip -----------------------------------------------------
if [[ "${METHOD,,}" == *"skullstrip"* ]] \
|| [[ "${METHOD,,}" == *"afni"* ]]; then
  if [[ "${VERBOSE}" == "true" ]]; then echo ">>>Running AFNI 3dSkullstrip"; fi
  3dSkullStrip \
    -input ${IMAGE[0]} \
    -prefix ${DIR_SCRATCH}/${PREFIX}_mask-${LABEL}+AFNI${SUFFIX}.nii.gz
  fslmaths ${DIR_SCRATCH}/${PREFIX}_mask-${LABEL}+AFNI${SUFFIX}.nii.gz \
    -bin ${DIR_SCRATCH}/${PREFIX}_mask-${LABEL}+AFNI${SUFFIX}.nii.gz
  MASK_LS+=(${PREFIX}_mask-${LABEL}+AFNI${SUFFIX}.nii.gz)
fi

# run AFNI 3dAutomask -----------------------------------------------------
if [[ "${METHOD,,}" == *"automask"* ]]; then
  if [[ "${VERBOSE}" == "true" ]]; then echo ">>>Running AFNI 3dAutomask"; fi
  3dAutomask \
    -prefix ${DIR_SCRATCH}/${PREFIX}_mask-${LABEL}+AUTO${SUFFIX}.nii.gz \
    -clfrac ${AUTOMASK_CLIP} -q \
    ${IMAGE[0]}
  CopyImageHeaderInformation ${IMAGE[0]} \
    ${DIR_SCRATCH}/${PREFIX}_mask-${LABEL}+AUTO${SUFFIX}.nii.gz \
    ${DIR_SCRATCH}/${PREFIX}_mask-${LABEL}+AUTO${SUFFIX}.nii.gz 1 1 1
  MASK_LS+=(${PREFIX}_mask-${LABEL}+AUTO${SUFFIX}.nii.gz)
fi

# run ANTs brain extraction -------------------------------------------------
if [[ "${METHOD,,}" == *"ants"* ]]; then
  if [[ "${VERBOSE}" == "true" ]]; then echo ">>>Running ANTs Brain Extraction"; fi
  DIR_TEMPLATE=${INC_TEMPLATE}/${TEMPLATE}
  ants_fcn="antsBrainExtraction.sh"
  ants_fcn="${ants_fcn} -d 3"
  for (( j=0; j<${#IMAGE[@]}; j++ )); do
    ants_fcn="${ants_fcn} -a ${IMAGE[${j}]}"
  done
  ants_fcn="${ants_fcn} -e ${DIR_TEMPLATE}/T_template0.nii.gz"
  ants_fcn="${ants_fcn} -m ${DIR_TEMPLATE}/T_template0_BrainCerebellumProbabilityMask.nii.gz"
  ants_fcn="${ants_fcn} -f ${DIR_TEMPLATE}/T_template0_BrainCerebellumRegistrationMask.nii.gz"
  ants_fcn="${ants_fcn} -o ${DIR_SCRATCH}/ants-bex_"
  eval ${ants_fcn}
  CopyImageHeaderInformation ${IMAGE[${j}]} \
    ${DIR_SCRATCH}/ants-bex_BrainExtractionMask.nii.gz \
    ${DIR_SCRATCH}/ants-bex_BrainExtractionMask.nii.gz 1 1 1
  mv ${DIR_SCRATCH}/ants-bex_BrainExtractionMask.nii.gz \
    ${DIR_SCRATCH}/${PREFIX}_mask-${LABEL}+ANTs${SUFFIX}.nii.gz
  rm ${DIR_SCRATCH}/ants-bex_BrainExtraction*
  MASK_LS+=(${PREFIX}_mask-${LABEL}+ANTs${SUFFIX}.nii.gz)
fi

# run FSL's BET -------------------------------------------------------------
if [[ "${METHOD,,}" == *"fsl"* ]] || [[ "${METHOD,,}" == *"bet"* ]]; then
  if [[ "${VERBOSE}" == "true" ]]; then echo ">>>Running FSL's BET"; fi
  fsl_fcn="bet ${IMAGE[0]}"
  fsl_fcn="${fsl_fcn} ${DIR_SCRATCH}/fsl_bet.nii.gz"
  if [[ ${#IMAGE[@]} -gt 1 ]]; then
    fsl_fcn="${fsl_fcn} -A2 ${IMAGE[1]}"
  fi
  fsl_fcn="${fsl_fcn} -m -R"
  eval ${fsl_fcn}
  mv ${DIR_SCRATCH}/fsl_bet_mask.nii.gz ${DIR_SCRATCH}/${PREFIX}_mask-${LABEL}+FSL${SUFFIX}.nii.gz
  MASK_LS+=(${PREFIX}_mask-${LABEL}+FSL${SUFFIX}.nii.gz)
fi

# run FSL's BET for B0-------------------------------------------------------------
if [[ "${METHOD,,}" == *"b0"* ]]; then
  if [[ "${VERBOSE}" == "true" ]]; then echo ">>>Running FSL's BET on B0"; fi
  fsl_fcn="bet ${IMAGE[0]}"
  fsl_fcn="${fsl_fcn} ${DIR_SCRATCH}/fsl_bet.nii.gz"
  fsl_fcn="${fsl_fcn} -m -n"
  eval ${fsl_fcn}
  mv ${DIR_SCRATCH}/fsl_bet_mask.nii.gz ${DIR_SCRATCH}/${PREFIX}_mod-B0_mask-${LABEL}+FSL${SUFFIX}.nii.gz
  MASK_LS+=(${PREFIX}_mod-B0_mask-${LABEL}+FSL${SUFFIX}.nii.gz)
fi

# SAMSEG labelling for brain mask ----------------------------------------------
if [[ "${METHOD,,}" == *"fsurf"* ]] \
|| [[ "${METHOD,,}" == *"freesurfer"* ]] \
|| [[ "${METHOD,,}" == *"samseg"* ]]; then
  if [[ "${VERBOSE}" == "true" ]]; then echo ">>>Running Freesurfer's SAMSEG"; fi
  mkdir -p ${DIR_SCRATCH}/samseg
  samseg_fcn="run_samseg --input"
  for (( j=0; j<${#IMAGE[@]}; j++ )); do
    mri_convert ${IMAGE[${j}]} ${DIR_SCRATCH}/image${j}.mgz
    samseg_fcn="${samseg_fcn} ${DIR_SCRATCH}/image${j}.mgz"
  done
  samseg_fcn="${samseg_fcn} --output ${DIR_SCRATCH}/samseg"
  eval ${samseg_fcn}
  mri_extract_label ${DIR_SCRATCH}/samseg/seg.mgz \
    0 4 24 43 165 258 259 ${DIR_SCRATCH}/samseg/nonbrain.mgz
  mri_convert ${DIR_SCRATCH}/samseg/nonbrain.mgz ${DIR_SCRATCH}/samseg/nonbrain.nii.gz
  mri_convert ${DIR_SCRATCH}/samseg/seg.mgz ${DIR_SCRATCH}/samseg/brain.nii.gz
  fslmaths ${DIR_SCRATCH}/samseg/nonbrain.nii.gz \
    -binv ${DIR_SCRATCH}/samseg/nonbrain.nii.gz
  fslmaths ${DIR_SCRATCH}/samseg/brain.nii.gz \
    -bin -mas ${DIR_SCRATCH}/samseg/nonbrain.nii.gz \
    ${DIR_SCRATCH}/${PREFIX}_mask-${LABEL}+SAMSEG${SUFFIX}.nii.gz
  MASK_LS+=(${PREFIX}_mask-${LABEL}+SAMSEG${SUFFIX}.nii.gz)
fi

if [[ "${SPATIAL_FILTER,,}" != "null" ]]; then
  if [[ "${VERBOSE}" == "true" ]]; then echo ">>>>>>applying Spatial Filter ${SPATIAL_FILTER} ${FILTER_RADIUS}"; fi
  for (( i=0; i<${#MASK_LS[@]}; i++ )); do
    sf_fcn="ImageMath 3 ${DIR_SCRATCH}/${MASK_LS[${i}]}"
    sf_fcn="${sf_fcn} ${SPATIAL_FILTER}"
    sf_fcn="${sf_fcn} ${DIR_SCRATCH}/${MASK_LS[${i}]}"
    sf_fcn="${sf_fcn} ${FILTER_RADIUS}"
    eval ${sf_fcn}
  done
fi

# do majority vote mask if multiple used ---------------------------------------
METHOD=(${METHOD//,/ })
if [[ ${#METHOD[@]} > 1 ]]; then
  for (( i=0; i<${#MASK_LS[@]}; i++ )); do
    TLS="${TLS},${DIR_SCRATCH}/${MASK_LS[${i}]}"
  done

  ## make VENN mask labelling overlapping regions in labels
  if [[ "${VERBOSE}" == "true" ]]; then echo ">>>Running making Venn-like overlap of masks"; fi
  maskVenn --mask-ls ${TLS} --label "brain+VENN${SUFFIX}" --prefix ${PREFIX} --dir-save ${DIR_SCRATCH}
  MASK_LS+=(${PREFIX}_mask-${LABEL}+VENN${SUFFIX}.nii.gz)

  ## make MAJORITY VOTE for brain mask
  if [[ "${VERBOSE}" == "true" ]]; then echo ">>>Running majority vote of masks"; fi
  ImageMath 3 ${DIR_SCRATCH}/${PREFIX}_mask-${LABEL}+MALF${SUFFIX}.nii.gz MajorityVoting ${TLS//,/ }
  MASK_LS+=(${PREFIX}_mask-${LABEL}+MALF${SUFFIX}.nii.gz)

  ## make INTERSECTION mask
  INTERSECT=$(ezMath -x "2^${#METHOD[@]}-1" -d 0)
  fslmaths ${DIR_SCRATCH}/${PREFIX}_mask-${LABEL}+VENN${SUFFIX}.nii.gz \
    -thr ${INTERSECT} -uthr ${INTERSECT} -bin \
    ${DIR_SCRATCH}/${PREFIX}_mask-${LABEL}+INTERSECT${SUFFIX}.nii.gz
  MASK_LS+=(${PREFIX}_mask-${LABEL}+INTERSECT${SUFFIX}.nii.gz)

  ## make UNION mask
  fslmaths ${DIR_SCRATCH}/${PREFIX}_mask-${LABEL}+VENN${SUFFIX}.nii.gz \
    -bin ${DIR_SCRATCH}/${PREFIX}_mask-${LABEL}+UNION${SUFFIX}.nii.gz
  MASK_LS+=(${PREFIX}_mask-${LABEL}+UNION${SUFFIX}.nii.gz)
fi

# make PNG ---------------------------------------------------------------------
if [[ "${NO_PNG}" == "false" ]]; then
  for (( i=0; i<${#MASK_LS[@]}; i++ )); do
    unset png_fcn
    TNAME=${MASK_LS[${i}]%%.*}
    png_fcn="make3Dpng --bg ${IMAGE[0]}"
    png_fcn=${png_fcn}' --bg-threshold "5,99"'
    if [[ "${TNAME}" == *"VENN"* ]]; then
      png_fcn="${png_fcn} --fg ${DIR_SCRATCH}/${MASK_LS[${i}]}"
      png_fcn=${png_fcn}' --fg-color "timbow"'
      png_fcn=${png_fcn}' --fg-order "random"'
      png_fcn=${png_fcn}' --fg-alpha 50'
      png_fcn=${png_fcn}' --fg-cbar'
    else
      png_fcn="${png_fcn} --roi ${DIR_SCRATCH}/${MASK_LS[${i}]}"
      png_fcn=${png_fcn}' --roi-color "#FF0000"'
    fi
    png_fcn=${png_fcn}' --layout "9:x;9:x;9:x;9:y;9:y;9:y;9:z;9:z;9:z"'
    png_fcn=${png_fcn}' --offset "0,0,0"'
    png_fcn="${png_fcn} --filename ${TNAME}"
    png_fcn="${png_fcn} --dir-save ${DIR_SCRATCH}"
    eval ${png_fcn}
  done
fi

# move files to appropriate locations-------------------------------------------
mv ${DIR_SCRATCH}/*_mask-${LABEL}* ${DIR_SAVE}/


#===============================================================================
# End of Function
#===============================================================================
exit 0


