#!/bin/bash -e
#===============================================================================
# Autodownload files from xnat
# Authors: Timothy R. Koscik
# Date: 2021-01-27
#===============================================================================
PROC_START=$(date +%Y-%m-%dT%H:%M:%S%z)
FCN_NAME=($(basename "$0"))
DATE_SUFFIX=$(date +%Y%m%dT%H%M%S%N)
OPERATOR=$(whoami)
KERNEL="$(uname -s)"
HARDWARE="$(uname -m)"
HPC_Q=${QUEUE}
if [[ -n ${HPC_Q} ]]; then HPC_Q="NA"; fi
HPC_SLOTS=${NSLOTS}
if [[ -n ${HPC_SLOTS} ]]; then HPC_SLOTS="NA"; fi
umask 007

# actions on exit --------------------------------------------------------------
## capture time, exit code, write to benchmark log
function egress {
  EXIT_CODE=$?
  PROC_STOP=$(date +%Y-%m-%dT%H:%M:%S%z)
  logBenchmark --operator ${OPERATOR} \
  --hardware ${HARDWARE} --kernel ${KERNEL} --hpc-q ${HPC_Q} --hpc-slots ${HPC_SLOTS} \
  --fcn-name ${FCN_NAME} --proc-start ${PROC_START} --proc-stop ${PROC_STOP} --exit-code ${EXIT_CODE}
}
trap egress EXIT

#===============================================================================
# Start of Function
#===============================================================================
PROJECT_LS=($(getColumn -i ${INC_DB}/projects.tsv -f xnat_project))
N=${#PROJECT[@]}
for (( i=1; i<${N}; i++ )); do
  dicomDownload --xnat-project ${PROJECT_LS[${i}]}
done

#===============================================================================
# End of Function
#===============================================================================
exit 0

