#!/bin/bash -e
#===============================================================================
# Initialize Diffusion Preprocessing
# - select dwi files to process together
# - setup working directory, persistent across sections
# Authors: Timothy R. Koscik
# Date: 2020-06-16
#===============================================================================
PROC_START=$(date +%Y-%m-%dT%H:%M:%S%z)
FCN_NAME=($(basename "$0"))
DATE_SUFFIX=$(date +%Y%m%dT%H%M%S%N)
OPERATOR=$(whoami)
KERNEL="$(uname -s)"
HARDWARE="$(uname -m)"
HPC_Q=${QUEUE}
HPC_SLOTS=${NSLOTS}
KEEP=false
NO_LOG=false
umask 007

# actions on exit, write to logs, clean scratch
function egress {
  EXIT_CODE=$?
  PROC_STOP=$(date +%Y-%m-%dT%H:%M:%S%z)
  if [[ "${KEEP}" == "false" ]]; then
    if [[ -n ${DIR_SCRATCH} ]]; then
      if [[ -d ${DIR_SCRATCH} ]]; then
        if [[ "$(ls -A ${DIR_SCRATCH})" ]]; then
          rm -R ${DIR_SCRATCH}
        else
          rmdir ${DIR_SCRATCH}
        fi
      fi
    fi
  fi
  if [[ "${NO_LOG}" == "false" ]]; then
    unset LOGSTR
    LOGSTR="${OPERATOR},${DIR_PROJECT},${PID},${SID},${HARDWARE},${KERNEL},${HPC_Q},${HPC_SLOTS},${FCN_NAME},${PROC_START},${PROC_STOP},${EXIT_CODE}"
    writeLog --benchmark --string ${LOGSTR}
  fi
}
trap egress EXIT

# Parse inputs -----------------------------------------------------------------
OPTS=$(getopt -o hlv --long prefix:,\
dwi:,dir-prep:,\
help,no-log,verbose -n 'parse-options' -- "$@")
if [ $? != 0 ]; then
  echo "Failed parsing options" >&2
  exit 1
fi
eval set -- "$OPTS"

# Set default values for function ---------------------------------------------
PREFIX=
DWI=
DIR_PREP=
HELP=false
VERBOSE=false

while true; do
  case "$1" in
    -h | --help) HELP=true ; shift ;;
    -l | --no-log) NO_LOG=true ; shift ;;
    -v | --verbose) VERBOSE=true ; shift ;;
    --prefix) PREFIX="$2" ; shift 2 ;;
    --dwi) DWI="$2" ; shift 2 ;;
    --dir-prep) DIR_PREP="$2" ; shift 2 ;;
    -- ) shift ; break ;;
    * ) break ;;
  esac
done

# Usage Help -------------------------------------------------------------------
if [[ "${HELP}" == "true" ]]; then
  echo ''
  echo '------------------------------------------------------------------------'
  echo "Iowa Neuroimage Processing Core: ${FCN_NAME}"
  echo '------------------------------------------------------------------------'
  echo '  -h | --help              display command help'
  echo '  -l | --no-log            disable writing to output log'
  echo '  -v | --verbose           verbose, returns teemporary folder path'
  echo '  --prefix                 scan prefix, default: sub-123_ses-1234abcd'
  echo '  --dwi                    Comma-separated list of DWI files to process'
  echo '                           together'
  echo '  --dir-prep               directory to copy dwi files for processing'
  echo '                           will be persistent after function'
  echo ''
  NO_LOG=true
  exit 0
fi

#===============================================================================
# Start of Function
#===============================================================================
DWI=(${DWI//,/ })
N_DWI=${#DWI[@]}

# Set up BIDs compliant variables and workspace --------------------------------
DIR_PROJECT=$(getDir -i ${DWI[0]})
PROJECT=$(getProject -i ${DWI[0]})
PID=$(getField -i ${DWI[0]} -f sub)
SID=$(getField -i ${DWI[0]} -f ses)
if [[ -z "${PREFIX}" ]]; then
  PREFIX="sub-${PID}"
  if [[ -n ${SID} ]]; then
    PREFIX="${PREFIX}_ses-${SID}"
  fi
fi
if [[ -z ${DIR_PREP} ]]; then
  DIR_PREP=${DIR_TMP}/${PROJECT}_${PREFIX}_DWIprep_${DATE_SUFFIX}
fi
mkdir -p ${DIR_PREP}

for (( i=0; i<${N_DWI}; i++ )); do
  NAME_BASE=${DWI[${i}]}
  NAME_BASE=${NAME_BASE::-7}
  cp ${DWI[${i}]} ${DIR_PREP}/
  cp ${NAME_BASE}.json ${DIR_PREP}/
  cp ${NAME_BASE}.bval ${DIR_PREP}/
  cp ${NAME_BASE}.bvec ${DIR_PREP}/
done
if [[ "${VERBOSE}" == "true" ]]; then
  echo ${DIR_PREP}
fi

#===============================================================================
# End of Function
#===============================================================================
exit 0

