#!/bin/bash -e

OPTS=$(getopt -o hx:d: --long expression:,digits:,help -n 'parse-options' -- "$@")
if [[ $? != 0 ]]; then echo "Failed parsing options" >&2; exit 1; fi
eval set -- "$OPTS"

EXPRESSION=
DIGITS=3
HELP="false"

while true; do
  case "$1" in
    -h | --help) HELP="true" ; shift ;;
    -x | --expression) EXPRESSION="$2" ; shift 2 ;;
    -d | --digits) DIGITS="$2" ; shift 2 ;;
    -- ) shift ; break ;;
    * ) break ;;
  esac
done

# Usage Help -------------------------------------------------------------------
if [[ "${HELP}" == "true" ]]; then
  echo ''
  echo '------------------------------------------------------------------------'
  echo "Iowa Neuroimage Processing Core: ${FCN_NAME}"
  echo '------------------------------------------------------------------------'
  echo '-h | --help           display command help'
  echo '-x | --expression     mathematical expression, for bc'
  echo '-d | --digits         number of digits to round to'
  echo ''
  exit 0
fi

printf '%.*f\n' "${DIGITS}" "$(bc -l <<< "a=${EXPRESSION}; if(a>0) a+=5/10^(${DIGITS}+1) else if (a<0) a-=5/10^(${DIGITS}+1); scale=${DIGITS}; a/1")"

#ANSWER=$(echo "${EXPRESSION}" | bc -l)
#ROUND_FCN="$(printf '%.${DIGITS}f', ${ANSWER})"
#echo ${ROUND_FCN}
#ROUNDED=$(eval ${ROUND_FCN})
#echo ${ROUNDED}

