#!/bin/bash -e
#===============================================================================
# change flags in BIDS filename
# compliant with BIDs 1.2.2, and includes INPC-specific extensions
# Authors: Timothy R. Koscik, PhD
# Date: 2020-03-09
#===============================================================================

# Parse inputs -----------------------------------------------------------------
OPTS=$(getopt -o hmadi:f:v: --long input:,modify,add,delete,field:,value:,help -n 'parse-options' -- "$@")
if [[ $? != 0 ]]; then
  echo "Failed parsing options" >&2
  exit 1
fi
eval set -- "$OPTS"

# Set default values for function ---------------------------------------------
INPUT=
FIELD=
VALUE_NEW=
ACTION=
HELP=false

while true; do
  case "$1" in
    -h | --help) HELP=true ; shift ;;
    -i | --input) INPUT="$2" ; shift 2 ;;
    -m | --modify) ACTION=modify ; shift ;;
    -a | --add) ACTION=add ; shift ;;
    -d | --delete) ACTION=delete ; shift ;;
    -f | --field) FIELD="$2" ; shift 2 ;;
    -v | --value) VALUE_NEW="$2" ; shift 2 ;;
    -- ) shift ; break ;;
    * ) break ;;
  esac
done

# Usage Help -------------------------------------------------------------------
if [[ "${HELP}" == "true" ]]; then
  echo ''
  echo '------------------------------------------------------------------------'
  echo "Iowa Neuroimage Processing Core: ${FCN_NAME}"
  echo '------------------------------------------------------------------------'
  echo '  -h | --help              display command help'
  echo '  -i | --input <value>     BIDs compliant filepath'
  echo '  -m | --modify            modify an existing flag'
  echo '  -a | --add               add an additional flag'
  echo '  -d | --delete            delete an existing flag'
  echo '  -f | --field <value>     field to act on'
  echo '  -v | --value <value>     value to use'
  echo '  field options (in order):'
  echo '    sub, ses, task, acq, ce, rec, dir, run, mod*, echo, recording, proc,'
  echo '    site, mask, label, from, to, reg, prep, resid, xfm'
  echo '    modality [image modality at end of filename]'
  echo '    [*mod refers to "mod" as a flag, not the mdality without a flag at'
  echo '     the end of the filename]'
  echo '    -novel field will be appended before modality'
  echo ''
  exit 0
fi

#==============================================================================
# Start of function
#==============================================================================
# extract directory, filename, and extension ----------------------------------
DIR_NAME=$(dirname ${INPUT})
if [[ "${DIR_NAME}" == "." ]]; then DIR_NAME=null; fi
BNAME=$(basename ${INPUT})
FNAME="${BNAME%%.*}"
EXT="${BNAME#*.}"

# extract flags and values ----------------------------------------------------
SPLIT_UNDERSCORE=(${FNAME//_/ })
for (( i=0; i<${#TEMP[@]}; i++ )); do
  unset SPLIT_DASH
  SPLIT_DASH=(${SPLIT_UNDERSCORE[${i}]//-/ })
  if [[ ${#SPLIT_DASH[@]} -eq 2 ]]; then
    FLAG+=(${SPLIT_DASH[0]})
    VALUE+=(${SPLIT_DASH[1]})
  else
    FLAG+=(modality)
    VALUE+=(${SPLIT_DASH[0]})
  fi
done
NFLAG=${#FLAG[@]}

# loop over possible flags, modify, add, or delete-----------------------------
## modify flag ----------------------------------------------------------------
if [[ "${ACTION,,}" == "modify" ]]; then
  for (( i=0; i<${NFLAG}; i++ )); do
    if [[ "${FLAG[${i}],,}" == "${FIELD,,}" ]]; then
      VALUE[${i}]="${VALUE_NEW}"
    fi
  done
fi

## delete flag ----------------------------------------------------------------
if [[ "${ACTION,,}" == "delete" ]]; then
  for (( i=0; i<${NFLAG}; i++ )); do
    if [[ "${FLAG[${i}]}" == "${FIELD,,}" ]]; then
      FLAG[${i}]="delete"
      VALUE[${i}]="delete"
    fi
  done
fi

## Add flag -------------------------------------------------------------------
BIDS_LS=("sub" "ses" "task" "acq" "ce" "rec" "dir" "run" "mod" "echo" "recording" "proc" "site" "mask" "label" "from" "to" "reg" "prep" "resid" "xfm")
N_BIDS=${#BIDS_LS[@]}
if [[ "${ACTION,,}" == "add" ]]; then
  TFLAG=
  TVALUE=
  for (( i=0; i<${N_BIDS}; i++ )); do
    if [[ "${FIELD,,}" == "${BIDS_LS[${i}]}" ]]; then
      TFLAG+=(${FIELD,,})
      TVALUE+=(${VALUE_NEW})
    fi
    for (( j=0; j<${NFLAG}; j++ )); do
      if [[ "${FLAG[${j}]}" == "${BIDS_LS[${i}]}" ]]; then
        TFLAG+=(${FLAG[${j}]})
        TVALUE+=(${VALUE[${j}]})
      fi
    done
  done
  if [[ ! "${BIDS_LS[@]}" =~ "${FIELD,,}" ]]; then
    TFLAG+=(${FIELD,,})
    TVALUE+=(${VALUE_NEW})
  fi
  FLAG=(${TFLAG[@]})
  VALUE=(${TVALUE[@]})
fi

# write output string ---------------------------------------------------------
OUT_STR=
if [[ "${DIR_NAME}" !="null" ]]; then OUT_STR="${DIR_NAME}/"; fi
for (( i=0; i<${#FLAG[@]}; i++ )); do
  if [[ "${FLAG[${i}]}" != "delete" ]]; then
    if [[ "${FLAG[${i}]}" != "modality" ]]; then
      OUT_STR="${OUT_STR}${FLAG[${i}]}-${VALUE[${i}]}_"
    else
      OUT_STR="${OUT_STR}${VALUE[${i}]}"
    fi
  fi
done
if [[ -n ${EXT} ]]; then OUT_STR="${OUT_STR}.${EXT}"; fi

# send output to terminal -----------------------------------------------------
echo ${OUT_STR}

#==============================================================================
# End of function
#==============================================================================
exit 0

